### ISSUE TITLE
Esquema de tradução - versão 1

### ISSUE THREAD

**Issue by tiagoboeing** [tiagoboeing/compiladores#16]
Implementar 1ª versão do esquema de tradução conforme especificações da folha.
Analisador semântico e gerador de código.

- [Esquema de tradução - versão 1](https://github.com/tiagoboeing/compiladores/wiki/Esquema-de-tradu%C3%A7%C3%A3o---vers%C3%A3o-1)
- [Ações dos esquemas de tradução](https://github.com/tiagoboeing/compiladores/wiki/Esquemas-de-tradu%C3%A7%C3%A3o)

### ilasm
No Windows o caminho para o ilasm é
`C:\Windows\Microsoft.NET\Framework64\v4.0.30319`

**Comment by tiagoboeing** [comment]
O branch **[esquema-de-traducao-versao-1](https://github.com/tiagoboeing/compiladores/tree/esquema-de-traducao-versao-1)** possui as implementações em andamento, é importante lembrar que as mensagens de erros implementadas anteriormente foram substituídas pelas padrões do GALS de acordo com sugestões da professora. 

Ela orientou para ao final de todo o processo do semântico voltarmos com as mensagens de erros implementadas no sintático, já que ainda será necessário gerar código no GALS outras vezes.

A issue #17 foi criada para não esquecermos.

**Comment by tiagoboeing** [comment]
Cenário utilizado para testes:
Branch **semantic_new_structure**

## Testes executados:

- Imprimir inteiros (1234) ✅
- Imprimir float (123.4) ✅
- Imprimir float negativo (-1234.2) ✅
- Imprimir float positivo com sinal (+123.1) ✅
- Imprimir número positivo com sinal (+1234) ✅
- Teste de menos com menos = mais (1--1) ✅
- Divisão: (1/1) ✅
- Divisão (10/2) = 5 ✅
- Divisão (10/3) = 3,3333... ✅
- Multiplicação (10*3) = 30 ✅

### Imprimir -1 ✅

```
main
begin
	write(-1).
end
```
Saída: -1 

------------

### Operações entre inteiros ✅

```
main
begin
	write(-1+1).
end
```

Saída: 0

-----------

### Soma entre dois negativos ✅

```
main
begin
	write(-1+-1).
end
```

Saída: -2

> Testado também subtração

----------

**Comment by katherinespiess** [comment]
Lembrar de testar:

```
write(1>2)
write(1<2)
write(2>1)
write(2<1)
write(2=1)
write(2=2)
```
✅

**Comment by katherinespiess** [comment]
Testar declaração de variável:

```
int : var1, var2.
read(var1, var2).
write(var1 + var2).
```

✅

**Comment by tiagoboeing** [comment]
Erro encontrado ao tentar somar:
- float + float ❌
- float + int64 ❌

Tirar dúvida sobre operador de atribuição.

**Comment by tiagoboeing** [comment]
> Erro encontrado ao tentar somar:
> 
> * float + float ❌
> * float + int64 ❌
> 
> Tirar dúvida sobre operador de atribuição.

Em relação a este comentário, o código está certo. No terminal devemos utilizar `,` para separar a casa decimal e não `.`

`10,0 + 10,0`

**Comment by tiagoboeing** [comment]
@gustavospiess vamos continuar as implementações na issue #19
