### ISSUE TITLE
3º passo

### ISSUE THREAD

**Issue by tiagoboeing** [tiagoboeing/compiladores#7]
Implementar o analisador sintático, bem como o tratamento de erros sintáticos, conforme especificado abaixo: 

![image](https://user-images.githubusercontent.com/3449932/58363295-0c5b5c00-7e78-11e9-818e-412ae2c10fd9.png)

![image](https://user-images.githubusercontent.com/3449932/58363298-1ed59580-7e78-11e9-9394-503286283cdc.png)

**Comment by katherinespiess** [comment]
- Mensagens de erro. Corrigir o array que o gaus criou.
 - Consumir o sintático. Criar uma interface/class que faça o acesso ao código gerado.
 - Output. Apresentar as mensagens conforme descrito.
